format own player: "&6Your playtime is &e{Days} &6days, &e{Hours} &6hours, &e{Minutes} &6minutes, &e{Seconds} &6seconds."
format other player: "&6Playtime of {PlayerName} is &e{Days} &6days, &e{Hours} &6hours, &e{Minutes} &6minutes, &e{Seconds} &6seconds."
player not found: "&cThis player not exists or is not connected."

MySQL:
  # Set to 'true' to use MySQL instead of SQLite for data storage.
  Enabled: false
  Hostname: localhost
  Port: 3306
  Database: your-database
  Username: user
  Password: pass
