#  _____  _             _   _
# |  __ \| |           | | (_)
# | |__) | | __ _ _   _| |_ _ _ __ ___   ___
# |  ___/| |/ _` | | | | __| | '_ ` _ \ / _ \
# | |    | | (_| | |_| | |_| | | | | | |  __/
# |_|    |_|\__,_|\__, |\__|_|_| |_| |_|\___|
#                  __/ |
#                 |___/
#
# Playtime - config.yml - Main Configuration
# Copyright 2020 Zach_FR | All Rights Reserved
#
#  Helpful Links:
#   Support |   https://discord.zachfr.com
#   Docs    |   https://docs.zachfr.com

# Should reward function should be enable?
Reward: false

# Leaderboard option.
Leaderboard:
  # Should we use chat format or gui format?
  # Format: "chat" or "gui"
  Format: chat
  # This is only trigger if you use chat format.
  # You can use that placeholder: {playerrank}, {playernickname}, {playername}, {topnumber}, {days}, {hours}, {minutes}, {seconds}
  Chat:
    - "&7============== &6Playtime leaderboard &7=============="
    - "&6Top: {topnumber}, {playerrank} {playernickname} &6Days: &e{days}, &6Hours: &e{hours}, &6Minutes: &e{minutes}, &6Seconds: &e{seconds}"
    - "&6Top: {topnumber}, {playerrank} {playernickname} &6Days: &e{days}, &6Hours: &e{hours}, &6Minutes: &e{minutes}, &6Seconds: &e{seconds}"
    - "&6Top: {topnumber}, {playerrank} {playernickname} &6Days: &e{days}, &6Hours: &e{hours}, &6Minutes: &e{minutes}, &6Seconds: &e{seconds}"
    - "&6Top: {topnumber}, {playerrank} {playernickname} &6Days: &e{days}, &6Hours: &e{hours}, &6Minutes: &e{minutes}, &6Seconds: &e{seconds}"
    - "&6Top: {topnumber}, {playerrank} {playernickname} &6Days: &e{days}, &6Hours: &e{hours}, &6Minutes: &e{minutes}, &6Seconds: &e{seconds}"
    - "&6Top: {topnumber}, {playerrank} {playernickname} &6Days: &e{days}, &6Hours: &e{hours}, &6Minutes: &e{minutes}, &6Seconds: &e{seconds}"
    - "&6Top: {topnumber}, {playerrank} {playernickname} &6Days: &e{days}, &6Hours: &e{hours}, &6Minutes: &e{minutes}, &6Seconds: &e{seconds}"
    - "&6Top: {topnumber}, {playerrank} {playernickname} &6Days: &e{days}, &6Hours: &e{hours}, &6Minutes: &e{minutes}, &6Seconds: &e{seconds}"
    - "&6Top: {topnumber}, {playerrank} {playernickname} &6Days: &e{days}, &6Hours: &e{hours}, &6Minutes: &e{minutes}, &6Seconds: &e{seconds}"
    - "&6Top: {topnumber}, {playerrank} {playernickname} &6Days: &e{days}, &6Hours: &e{hours}, &6Minutes: &e{minutes}, &6Seconds: &e{seconds}"
    - "&7==============================================="
  # Placeholder available: {topnumber}
  Unclaimed position:
    # Show unclaimed postion message?
    Enable: true
    Message: "Position unclaimed"

# Storage option.
MySQL:
  # Set to 'true' to use MySQL instead of SQLite for data storage.
  Enabled: false
  Hostname: localhost
  Port: 3306
  Database: your-database
  Username: user
  Password: pass
