name: Playtime
version: ${project.version}
main: me.zachary.playtime.Playtime
api-version: 1.13
authors: [ Zach_FR ]
softdepend: [ PlaceholderAPI, Vault, LuckPerms ]
description: Get playtime from your player
