name: Playtime
version: ${project.version}
main: me.zachary.playtime.Playtime
api-version: 1.16
authors: [ Zach_FR ]
description: Run a /playtime and show playtime of

commands:
  playtime:
    description: Show your playtime
